version: "3"

services:
  django:
    build: ./src/backend/
    tty: true
    networks:
      - frontend

  nginx:
    build: ./src/nginx/
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Moscow
    networks:
      - frontend
    volumes:
      - ./src/frontend/build:/var/www/snek-gc.misha.im/
    depends_on:
      - django

networks:
  frontend: