version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      - TZ=Europe/Moscow
    networks:
      - frontend
    volumes:
      - ./src/backend/etc/nginx.conf:/etc/nginx/nginx.conf
      - shared_volume:/var/www/snek-gc.misha.im/
    depends_on:
      - npm
  
  npm:
    build: ./src/frontend/
    volumes:
      - shared_volume:/frontend/build

networks:
  frontend:

volumes:
  shared_volume: