version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    environment:
      - TZ=Europe/Moscow
    networks:
      - frontend
    volumes:
      - ./src/backend/etc/nginx.conf:/etc/nginx/nginx.conf
      - ./src/frontend/build/:/frontend/build/

networks:
  frontend: