version: "3"

services:
  django:
    build: ./src/backend/
    tty: true
    ports:
      - 8080:8080
    networks:
      - frontend
    volumes:
      - shared:/app/static/

  nginx:
    build: ./src/nginx/
    ports:
      - 80:80
      - 443:443
    environment:
      - TZ=Europe/Moscow
    networks:
      - frontend
    volumes:
      - ./src/frontend/build:/var/www/snek-gc.misha.im/
      - shared:/var/www/snek-gc.misha.im/static/drf/
    depends_on:
      - django

networks:
  frontend:

volumes:
  shared: