# Generated by Django 2.1.3 on 2018-11-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='type',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
