# Generated by Django 2.1.3 on 2018-11-10 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ray", "0003_auto_20181110_1758")]

    operations = [
        migrations.RenameField(
            model_name="animal", old_name="lined_by_two", new_name="liked_by_two"
        )
    ]
