# Generated by Django 2.1.3 on 2018-11-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("ray", "0004_auto_20181110_1814")]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="lat",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="animal",
            name="lon",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="animal", name="photo", field=models.TextField()
        ),
    ]
