# Generated by Django 2.1.3 on 2018-11-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("ray", "0008_task_persons_applied")]

    operations = [
        migrations.RenameField(model_name="task", old_name="name", new_name="title")
    ]
