# Generated by Django 2.1.3 on 2018-11-11 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ray', '0013_auto_20181111_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='persons_applied',
        ),
    ]
